### ISSUE TITLE
Package is broken with React@16

### ISSUE THREAD

**Issue by wesharehoodies** [amytych/react-escape-outside#1]
Hola,

Our project uses this package and  it broke with R16 and webpack 3. Are you still maintaining this and accepting PRs?

![bug react](https://user-images.githubusercontent.com/11220736/32503262-0f130116-c3dd-11e7-823e-cf95adbd7220.png)

**Comment by wesharehoodies** [comment]
Solved.

**Comment by amytych** [comment]
Hi, sorry that I have not responded, not sure why I didn't get a notification e-mail.

I'm glad you solved the issue, if you did so still using this package, PR is always welcome.

Cheers!
